# Generated by Django 3.1 on 2020-08-23 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pelaporan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataperizinan',
            name='id',
        ),
        migrations.RemoveField(
            model_name='jenispsu',
            name='id',
        ),
        migrations.AlterField(
            model_name='dataperizinan',
            name='id_data_proyek',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pelaporan.dataproyek'),
        ),
        migrations.AlterField(
            model_name='jenispsu',
            name='id_data_proyek',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pelaporan.dataproyek'),
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id_notifikasi', models.AutoField(primary_key=True, serialize=False)),
                ('isi_notifikasi', models.TextField()),
                ('id_data_perusahaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelaporan.dataperusahaan')),
            ],
        ),
    ]
