# Generated by Django 3.1 on 2020-09-04 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelaporan', '0002_auto_20200905_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifikasi',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notifikasi',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 5, 0, 34, 28, 950275)),
        ),
    ]
