# Generated by Django 3.1 on 2020-08-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelaporan', '0002_auto_20200823_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataperizinan',
            old_name='izin_penggunaam_bangunan',
            new_name='izin_penggunaan_bangunan',
        ),
    ]
