# Generated by Django 3.1 on 2020-08-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelaporan', '0004_auto_20200830_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataperusahaan',
            name='verified_admin',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataproyek',
            name='verified_admin_data_perizinan',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataproyek',
            name='verified_admin_data_proyek',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataproyek',
            name='verified_admin_jenis_psu',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataproyek',
            name='verified_admin_tipe_rumah',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
